/***
Problem: Dummy Text Generator
The program should take an array of words and generate a random sentence of a specified length.

Instructions:
1. Define an array of words containing different words of your choice (e.g., nouns, verbs, adjectives, etc.)
2. Ask the user to enter the desired length of the dummy text (in words).
3. Generate a random sentence of the specified length by randomly selecting words from the array.
4. Display the generated dummy text to the user.

Note: Make sure to handle invalid input, such as non-numeric input or negative numbers for the desired length. 
If the user provides invalid input, display an appropriate error message. 
Also, feel free to customize the array of words with any words you prefer for your dummy text generator.
**/ 

//Program start
var jsBtn = document.getElementById('jsBtn');
var show = document.getElementById('show');

//Dummy text genetor variable
var dummyText = [
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra accumsan bibendum. Mauris ipsum diam, scelerisque sed efficitur a, efficitur eu tellus. Maecenas quis nibh eu leo varius sollicitudin vel eu metus. Nulla sed scelerisque lorem. Fusce pretium mauris id rutrum feugiat. Nulla sodales tellus in mauris imperdiet, quis suscipit neque iaculis. Vivamus pulvinar tempor mi facilisis imperdiet. Proin nec ipsum massa. Vestibulum consequat eu nunc id ornare. Cras lectus purus, blandit fringilla convallis quis, egestas ac diam.',
    'Ut non magna nisl. Nullam efficitur volutpat libero, et tempor sapien cursus non. Vivamus facilisis turpis id nibh facilisis aliquet. Nullam sit amet nisl tempor, luctus justo in, bibendum massa. Nulla maximus vel nulla ac porta. Maecenas vulputate ligula quam, sit amet iaculis lorem semper eu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis tristique metus et viverra condimentum. Nam commodo eget felis vitae vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus ante arcu, ullamcorper et sapien eu, bibendum vestibulum quam.',
    'Donec sed elit lectus. Nunc vel auctor arcu. Nam lobortis, lorem ut volutpat laoreet, diam ligula sagittis nisi, vel dignissim enim enim quis nunc. Fusce in est fermentum, semper lorem sed, ultrices erat. Nullam posuere tincidunt velit, eget posuere est tincidunt ac. Aliquam scelerisque lobortis libero, vel pharetra nunc efficitur a. Pellentesque egestas interdum ex non euismod. Duis auctor blandit iaculis. Nam volutpat neque sit amet nibh posuere, sed sollicitudin lacus venenatis. Curabitur dignissim consectetur nisl non fermentum. Fusce dictum non nunc ut molestie. Proin diam libero, dictum in congue ut, consectetur faucibus turpis. Nulla eleifend posuere porttitor. Ut pharetra, ligula quis vestibulum gravida, diam libero laoreet urna, ut laoreet arcu arcu ut risus. Vestibulum congue, erat lacinia ornare sagittis, quam lectus ullamcorper urna, dapibus interdum ipsum sem vitae dolor.',
    'Nulla et dui quis sem lobortis tempor. Ut eget felis eget erat volutpat vulputate sed sit amet metus. Donec accumsan vehicula congue. Nam vel eros quis ex varius tristique quis a sapien. Pellentesque sed nulla venenatis, dignissim velit sed, hendrerit risus. Curabitur vel urna eu felis blandit suscipit vitae vel libero. Aenean turpis est, tincidunt ut lacinia nec, tincidunt et lacus. Vivamus mi nisi, eleifend in fermentum eget, malesuada vitae nunc. Nam vestibulum, turpis eget auctor pellentesque, nulla est venenatis diam, eget dapibus erat ipsum id enim. Aliquam sodales aliquet scelerisque. Etiam bibendum augue vitae fringilla maximus.',
    'Etiam quis sem dui. Praesent pretium, lacus eu imperdiet volutpat, libero nunc consectetur orci, eget venenatis nibh nisi id neque. Nullam convallis tincidunt diam ut condimentum. In eget dolor quis risus faucibus luctus. Phasellus efficitur vulputate mollis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas nisl arcu, euismod ut dui at, finibus congue mauris. Vivamus ac purus lectus. Nunc tempor porta neque, eget congue dui. Aliquam in tortor in purus ornare porta rutrum et lacus. Duis ultricies quis magna non pharetra. Proin at diam non justo egestas aliquam non a est. Duis et rhoncus nibh. Morbi porttitor vulputate tellus et volutpat.',
    'Nunc ornare, quam in iaculis ornare, velit sapien fringilla est, eget bibendum est tellus eu mauris. In sagittis augue a nibh scelerisque imperdiet. Ut nunc libero, mollis at nisl id, vestibulum egestas lacus. Maecenas tempus consequat eros, eu malesuada arcu interdum nec. Vestibulum nunc tellus, tincidunt vel iaculis vitae, semper eget felis. Quisque nec velit mollis, porttitor augue quis, interdum mi. Suspendisse ut interdum nulla. Pellentesque finibus enim sed sem bibendum tempor. Nulla facilisi. Maecenas fringilla nunc eget est suscipit eleifend. Interdum et malesuada fames ac ante ipsum primis in faucibus.',

    'Pellentesque eu quam volutpat, semper urna quis, consequat mauris. Sed sagittis sapien in ornare iaculis. Cras porttitor nisl vel justo ultricies aliquet. Vestibulum tincidunt facilisis mauris at consequat. Maecenas porttitor leo non risus tincidunt, fringilla venenatis est sollicitudin. Aliquam erat volutpat. Nullam eget velit vel libero feugiat tempor in non erat. Nam et egestas elit, sed luctus neque. Sed eu augue nisl. Ut vitae odio ut mauris lacinia tincidunt. Donec mollis mi tellus, in hendrerit turpis aliquam non.',

    'Morbi est ipsum, varius vitae venenatis sit amet, tincidunt ac est. Integer ac neque ut nibh iaculis dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rhoncus dui est, non hendrerit lectus iaculis nec. Nullam ac nisl diam. Morbi interdum, odio vel ultricies consectetur, libero erat mollis ante, non molestie neque urna ac purus. Duis porta tellus dui, et hendrerit sem tristique vitae. Mauris quis aliquet magna. Suspendisse potenti.',

    'Nunc cursus velit magna, id sollicitudin enim fringilla iaculis. Aenean feugiat, eros in faucibus lobortis, nisi neque tempus risus, eu vehicula ipsum purus non erat. Integer fermentum mollis diam, ut aliquet erat bibendum quis. Pellentesque vestibulum nibh at turpis aliquet, eu congue sapien facilisis. Nunc at sapien ac magna accumsan faucibus. Phasellus ac metus eget libero laoreet mollis. Mauris egestas tellus vel diam semper mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec suscipit, nulla et dictum sagittis, sapien diam lacinia justo, vulputate rutrum magna sapien eu tortor. Integer a suscipit magna, a ultricies mi. Morbi magna leo, bibendum et turpis ut, sodales ultrices lorem. Nam at tincidunt ex. Nullam ornare rhoncus odio, sed aliquam dolor accumsan at. Integer quis venenatis elit, et malesuada lectus. Sed sollicitudin lobortis lorem, et semper dolor.',

    'Vestibulum maximus eros sed arcu sagittis, a faucibus felis ultricies. Nam fringilla auctor ante sed consectetur. Etiam sit amet lectus elementum, vestibulum risus vitae, eleifend lacus. Suspendisse ultricies massa lorem, ut blandit diam ornare eget. Curabitur id lacus vitae velit consectetur lacinia. Nullam non eleifend purus. Fusce interdum risus metus, sed ornare ex pharetra iaculis. Nam et velit a nisl facilisis convallis. Etiam placerat congue lectus, condimentum hendrerit sem bibendum sit amet.',

    'Sed egestas purus eu euismod lacinia. Ut consectetur justo ac sem dictum mattis. Nullam malesuada tempor nisi, in lobortis nisl efficitur quis. In aliquet, est vitae pharetra vehicula, tellus leo maximus turpis, ac cursus felis eros vel dolor. Nunc enim dolor, rhoncus et mi et, viverra varius magna. Phasellus congue elit in ante hendrerit euismod. Integer quis lacus eu dui fringilla facilisis vel eu odio. Phasellus vel enim blandit, posuere odio quis, ullamcorper magna. Vestibulum finibus quis metus at suscipit. Aenean commodo, leo quis hendrerit mollis, urna nulla congue eros, eget pulvinar justo ex ut lorem. Donec sagittis condimentum mauris quis tempus. Donec sit amet ultrices lacus, tincidunt gravida tortor.',

    'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis condimentum luctus risus non cursus. Quisque faucibus sollicitudin ligula a ultrices. Aliquam eget est diam. Nulla fringilla sit amet erat et maximus. Donec tempus ultrices viverra. Pellentesque vel nisi turpis. Morbi vel gravida dui. Phasellus varius odio a interdum tincidunt. Etiam gravida mauris justo, sit amet blandit neque condimentum eget. Morbi nulla orci, volutpat et augue vel, blandit tempor leo. Praesent at imperdiet ante. Quisque consectetur lectus non mattis rhoncus.',

    'Nunc sodales, lacus vel consectetur tempus, urna felis elementum nulla, id vestibulum felis mi eu nisl. Etiam at sodales sem, eu venenatis diam. Donec gravida justo quis eleifend egestas. Nulla vitae laoreet neque. Duis eu justo aliquet dui dapibus ornare. Suspendisse viverra nibh quis elit facilisis, eget convallis nunc consequat. Vivamus tellus elit, laoreet id hendrerit ac, tristique eu urna. Quisque efficitur, urna id bibendum placerat, purus eros hendrerit turpis, vel elementum purus orci et orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed suscipit porta vehicula. Donec euismod nulla eu ullamcorper tempus.',

    'Nam euismod dui mi, vitae iaculis sem volutpat hendrerit. Suspendisse magna nibh, tempor rhoncus dignissim non, accumsan quis tortor. Nam porta in elit rhoncus pulvinar. Suspendisse sit amet velit blandit nibh tempus eleifend ac eget nulla. Quisque eu quam hendrerit, euismod lorem quis, euismod metus. Mauris in massa urna. Vivamus et ipsum iaculis, commodo elit ut, aliquet ipsum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras rhoncus metus vel mi vestibulum rutrum. Fusce vel sem ac dui convallis tempor eu eget nulla. Aliquam in velit at arcu gravida ornare. Etiam malesuada laoreet velit, quis mattis magna sodales quis. In scelerisque tellus et eleifend scelerisque.',

    'Vivamus in tortor sed orci sodales fermentum. Donec rutrum magna nec enim suscipit pharetra. Nulla nec lorem eu magna tempor fermentum. Nam congue neque a lectus viverra, nec imperdiet odio euismod. Ut hendrerit volutpat orci ut condimentum. Donec in dui nec sem malesuada molestie. Praesent in eros ac velit tempus tempus. Suspendisse sed posuere massa. Etiam ut placerat libero. Fusce varius vulputate dolor non pharetra. Curabitur vehicula tincidunt venenatis.',

    'Donec vitae vulputate urna. Fusce laoreet diam in erat luctus laoreet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam id congue sem. Vestibulum pellentesque, metus vel vehicula venenatis, turpis enim aliquam erat, a dignissim justo mauris sit amet magna. Cras justo odio, ultricies non vehicula interdum, malesuada eu quam. Aliquam sodales ullamcorper sem, sed accumsan magna placerat nec. Cras ut suscipit mi. Donec quis nunc non ipsum blandit dictum.',

    'Quisque ultrices elit eros. Nam ultrices at purus et feugiat. Nam eget metus eros. Sed gravida imperdiet felis, sed ultricies ex consectetur in. Quisque risus tellus, volutpat vitae luctus at, blandit eget ante. Vivamus eget auctor ligula, ac fermentum ipsum. Sed sit amet ipsum fermentum, tristique justo luctus, convallis risus. Nunc velit neque, tincidunt nec posuere in, tincidunt ac mauris. Nullam scelerisque ultrices tincidunt. Aliquam efficitur at mauris sed rutrum. Nunc condimentum semper dignissim. Quisque hendrerit consequat blandit. Donec fringilla at elit sit amet ultricies. Donec ut metus libero.',

    'Aliquam erat volutpat. Integer quis arcu a nunc commodo aliquet. Morbi convallis dignissim sollicitudin. Aenean libero magna, vulputate posuere erat at, maximus ultrices metus. Pellentesque nec nisl in diam ornare tincidunt. Proin sit amet risus a enim ultrices egestas quis quis dui. Duis interdum eget odio eu aliquam.',

    'Vivamus elementum nisi eget egestas aliquam. Nam dapibus, lorem ac semper rutrum, est urna elementum ligula, eget molestie lorem odio ac lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce ut ultricies augue, at sagittis enim. Sed malesuada arcu non justo aliquet suscipit. Ut id pellentesque odio. Aenean porta quam sit amet imperdiet commodo. Duis porttitor orci et diam gravida dignissim.',

    'Proin at purus tortor. Sed quis accumsan sem, fringilla eleifend dui. Donec eget placerat orci. Vivamus posuere ipsum sed varius aliquam. Integer ullamcorper, sapien in laoreet vestibulum, purus quam bibendum augue, non laoreet enim augue in magna. Maecenas elementum, lorem sed viverra consectetur, lorem arcu tincidunt purus, sed pellentesque lacus nibh at augue. Suspendisse urna nibh, faucibus at consectetur sed, tincidunt vel purus. Integer at ex feugiat, congue enim at, sagittis purus.',

    'Donec porta cursus diam, laoreet sagittis enim. Maecenas luctus commodo mauris non aliquam. Pellentesque et enim leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent dui ipsum, ullamcorper nec velit at, blandit finibus lacus. Curabitur ac sagittis erat, vitae vulputate elit. Quisque imperdiet neque nec auctor porttitor. Aliquam erat volutpat. Nulla lobortis lacus non bibendum finibus. Donec tristique nisi a finibus tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',

    'Vestibulum feugiat purus semper, congue felis commodo, condimentum ipsum. Nunc urna elit, pharetra pretium lorem at, accumsan dapibus massa. Quisque a volutpat sem. Donec lacinia dictum neque vel volutpat. Donec elementum mattis nisi eu dapibus. Sed sodales tempor pulvinar. Curabitur eget erat dapibus, auctor sapien pretium, vestibulum felis. Praesent ultrices volutpat semper.',
    'Maecenas libero metus, ultrices vel ipsum id, aliquet faucibus dui. Etiam id mauris porta, mattis arcu at, facilisis tellus. Duis tempor ante vel ligula iaculis dictum. Donec a arcu non lectus mattis interdum. Maecenas malesuada lectus non ex sollicitudin, at cursus tellus ullamcorper. Fusce auctor volutpat cursus. Nullam porttitor libero in gravida maximus. Etiam mattis urna in metus vulputate lacinia. Duis ut ante sed nisi consectetur dapibus at sit amet est. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla luctus sem vitae laoreet rutrum. Nunc sit amet nibh enim. Integer pharetra orci odio, et finibus erat interdum eget.',

'Donec ut neque eleifend lacus dignissim condimentum. In pharetra dictum sodales. Donec semper lorem sit amet diam sodales, dictum posuere lectus porta. Vivamus at sem et nisi dapibus iaculis. Fusce vulputate, quam eu fermentum ultrices, sem leo volutpat ligula, id ultricies mi justo at sem. Cras tincidunt ante tellus, ut efficitur risus maximus a. Etiam ultrices interdum est non laoreet. Vivamus vestibulum ligula nisl, et rhoncus nisl aliquam et. Mauris feugiat risus at ultrices mollis. Nam rutrum maximus egestas. Vestibulum placerat tortor ut ante fermentum, non sollicitudin eros finibus. Curabitur vitae tellus metus.',

'Nunc et ipsum sed lorem imperdiet aliquam. Donec ac ex lobortis, elementum sem ac, malesuada odio. Aliquam congue tortor vitae arcu tincidunt rutrum. In sapien nulla, maximus a mollis a, volutpat vel velit. Donec hendrerit diam nibh, a venenatis ex ultricies eu. Etiam rhoncus condimentum hendrerit. Etiam porttitor viverra placerat. Vivamus et leo posuere, porttitor turpis eget, dignissim tellus. Praesent vel facilisis justo. Mauris sit amet auctor ex. Morbi dapibus, nunc nec finibus egestas, tellus dui congue sapien, vel dignissim libero nunc in metus. Pellentesque euismod est sed felis viverra, id mollis dui feugiat. Mauris rutrum quam tempor risus imperdiet rhoncus. In elementum nisi id ipsum bibendum suscipit. Proin lacinia mauris nec auctor sollicitudin.',

'Integer sit amet vehicula ligula. Integer ut tortor non nibh pretium consectetur a et ex. Vestibulum lectus ex, posuere at risus ac, feugiat pretium enim. Praesent ex enim, condimentum non vehicula nec, sollicitudin vel magna. Pellentesque ac mi ligula. Nulla facilisi. Integer ut enim id magna tincidunt maximus. Cras scelerisque libero quis ligula scelerisque, nec interdum ipsum sodales. Maecenas vitae augue eu sapien dapibus sagittis. Donec porttitor lobortis massa vel dignissim. Etiam tincidunt, lacus quis congue vestibulum, neque orci ullamcorper nisl, sit amet fringilla nulla arcu eu diam. Duis congue faucibus risus, non fringilla massa fermentum vel. Aenean auctor cursus massa sed lobortis. In laoreet lectus est, eget cursus ex fermentum et.',

'Sed interdum dui id finibus interdum. Duis consequat augue at ante lobortis consequat. Integer in mattis elit. Phasellus dapibus metus volutpat, suscipit tellus in, molestie neque. Aliquam ut lectus ac nisi rhoncus mattis quis mattis mi. Proin ultrices augue in vestibulum efficitur. Quisque et porta dolor. Vivamus posuere sollicitudin turpis sit amet lobortis. Curabitur interdum, orci id interdum efficitur, dui enim egestas ipsum, vel rutrum ligula tellus nec libero. Sed a condimentum sem. Duis varius, risus et varius elementum, lacus urna tincidunt nisl, eu egestas dui diam non urna. In eget sapien vehicula, condimentum neque tempor, interdum dolor. In pretium nisi vitae felis sagittis porttitor. Maecenas sollicitudin ante id mattis vehicula. Praesent blandit mi dignissim neque efficitur, vitae sodales massa tincidunt. Nullam eu convallis risus.',

'Maecenas euismod mi sollicitudin lorem scelerisque malesuada. Cras vel consectetur enim, non suscipit justo. Cras ac ante dui. In tincidunt luctus odio eu tempus. Suspendisse mollis lorem risus, non euismod orci scelerisque a. Mauris sed nulla sed ante sollicitudin consequat. Praesent tempor sit amet eros eget tempor. Proin tristique mollis mattis. Etiam posuere porta ligula a ultricies. Aliquam iaculis non tortor id ornare.',

'Nam egestas ullamcorper nunc, ut malesuada nunc. Suspendisse condimentum eleifend feugiat. Aliquam at eros et velit venenatis elementum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas ante est, feugiat quis augue et, pharetra dapibus arcu. Praesent mattis bibendum purus, varius vestibulum quam congue sed. Morbi massa ex, imperdiet dignissim eleifend non, pellentesque ut diam. Integer facilisis nulla ut erat tempor euismod viverra id enim.',

'Nulla vel placerat diam. Nullam fermentum vehicula eros. Vivamus dignissim rhoncus quam ultrices interdum. Ut tincidunt, magna eget vestibulum tristique, tortor urna sodales velit, at bibendum neque mauris maximus dui. Fusce in augue sed mauris porttitor varius. Proin porta lorem odio, vel malesuada tortor sagittis nec. Fusce accumsan dui quis eros fermentum tempus. Etiam imperdiet libero lectus, pulvinar cursus metus tincidunt varius. Sed eget ex ipsum. Aliquam vitae libero feugiat, porta lectus in, auctor purus. Praesent posuere tincidunt diam, ac dapibus mi pulvinar sit amet. Suspendisse venenatis placerat facilisis.',

'Vestibulum eu massa pellentesque, efficitur lectus non, posuere mi. Curabitur id neque sed urna ornare ornare eu non nibh. Suspendisse ornare convallis augue, id mollis augue scelerisque at. Proin ac tortor eget dui gravida blandit. Donec bibendum metus eu dolor suscipit, ac imperdiet lorem euismod. Sed leo enim, suscipit id quam aliquam, porttitor congue ex. Ut ultricies arcu sit amet est pellentesque placerat. Nunc luctus at metus quis consectetur. Donec lacus dui, porta a nulla a, commodo accumsan nulla. Praesent interdum ullamcorper augue consectetur sagittis. Ut sed erat neque.',

'Cras id cursus sapien. Mauris eu mollis ante. Donec mi purus, condimentum a mauris non, aliquet venenatis dui. Nunc mattis euismod auctor. Duis porta, nulla eget convallis ultrices, sem tortor placerat ex, ac scelerisque eros risus sit amet orci. Vivamus tempus nulla non eros finibus, vitae tincidunt diam hendrerit. Donec consectetur purus tincidunt mollis egestas. Nunc ac consectetur nisl. Integer pulvinar, risus blandit aliquet maximus, ante sem tincidunt purus, in maximus orci purus at lectus. Curabitur scelerisque, eros in pharetra efficitur, augue sem ultrices risus, sed laoreet erat tellus id magna. Aliquam vitae pretium orci. Sed a iaculis ipsum. Mauris molestie eros eu leo varius hendrerit. Sed sed nisi vehicula felis tristique pulvinar. Sed dictum dapibus ligula sed tincidunt. Aenean gravida mi sed tellus consequat semper.',

'Mauris ultricies lorem vitae lacinia tempor. Vestibulum facilisis, lacus sed aliquam tincidunt, arcu dui gravida tellus, a placerat lacus justo ac eros. Nulla fringilla quis purus eu iaculis. Phasellus interdum diam et purus ullamcorper, sed posuere orci posuere. Ut aliquam justo nec quam consectetur, dignissim luctus ligula venenatis. Etiam vulputate mauris enim. Praesent bibendum vel massa a iaculis. Vestibulum et nisl lobortis, venenatis sem eu, varius dui. Curabitur at ultrices nunc, nec aliquet nulla. In egestas rutrum enim, ac sodales nunc feugiat pharetra. Suspendisse tempus erat ut eros dapibus, ac finibus ligula tincidunt. Donec sodales nisl quis elit vulputate, ut egestas tortor mattis. Aliquam laoreet auctor nisi, lobortis feugiat neque condimentum non. Duis turpis mi, consequat id placerat et, placerat in nunc.',

'In lobortis diam eu risus ultricies mattis. Pellentesque nunc libero, vulputate sit amet suscipit mattis, pharetra eget dolor. Nulla porta sapien viverra, malesuada nisi sed, pellentesque augue. Cras interdum, ipsum vel porttitor lobortis, urna tortor efficitur tellus, at consectetur purus dui non justo. Maecenas condimentum, mi a suscipit blandit, dolor velit imperdiet lectus, a dapibus leo purus id eros. Phasellus placerat metus eget blandit pretium. Curabitur nec aliquam lectus, eu varius lorem. Curabitur nibh erat, sollicitudin eget metus vitae, ultrices iaculis diam.',

'Nunc quis nisl non leo mattis efficitur vel ut nibh. Nullam convallis dui congue, tempus dui ut, molestie sem. Proin efficitur nec mi in placerat. Phasellus quam quam, consectetur sit amet sagittis in, gravida at arcu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque luctus lectus in erat consectetur posuere. Morbi dictum tellus ac purus feugiat commodo.',

'Proin non odio eget lacus elementum condimentum. Ut malesuada rhoncus tortor, non porttitor enim consectetur vel. Sed in leo id lorem sodales dictum tincidunt in nisl. In at felis pulvinar sapien rhoncus ornare pulvinar vitae est. Duis interdum eleifend justo et posuere. Aenean auctor purus sit amet urna mollis, in lacinia mi ultricies. Morbi tincidunt finibus sem, et consequat velit egestas et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed molestie consectetur massa, sed congue mauris pellentesque ac. Duis tincidunt rutrum eleifend. Integer a nisl in turpis aliquet vulputate.',

'Integer dictum est magna, a sollicitudin orci malesuada nec. Nullam varius, dui vitae dapibus hendrerit, nunc tellus vestibulum massa, et gravida nisl arcu mollis ligula. Praesent lacinia imperdiet erat, in laoreet neque suscipit a. Mauris elit risus, congue at dui vel, viverra ultricies ante. Duis aliquam dolor vitae dolor tempor, quis molestie lectus ultrices. Donec augue est, varius quis rutrum id, ultrices et nunc. In bibendum orci ipsum, eu lacinia nunc semper sed. Curabitur porttitor rhoncus dapibus. Nulla facilisi.',

'Pellentesque quam ipsum, semper nec feugiat a, laoreet vel urna. Nunc eget turpis nec turpis tristique tempor. Praesent odio nisi, consectetur quis sagittis imperdiet, accumsan nec metus. Nunc rutrum pretium aliquet. Sed a ex aliquet, tempor turpis in, aliquam est. Praesent dapibus, ipsum id maximus maximus, est dui facilisis dui, quis euismod ipsum risus ac turpis. Ut euismod, augue id imperdiet blandit, ligula magna placerat velit, vitae volutpat sem turpis fringilla sapien.',

'Vestibulum faucibus erat eget feugiat eleifend. Cras congue justo elit, ac elementum lorem varius quis. Proin a volutpat diam, non lacinia lorem. Phasellus finibus eros ac tortor convallis cursus. In ac libero ornare, mollis diam in, vehicula est. Maecenas tempor pellentesque nisl, in suscipit est dictum eget. Mauris sit amet dolor volutpat arcu aliquet ullamcorper. Fusce id tincidunt enim. In blandit tortor sed ultricies dignissim. Proin rhoncus odio elit, id finibus mauris interdum sed. Duis non ligula eu felis pharetra pellentesque et vel sapien.',

'Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam nec faucibus enim. Aliquam in libero mauris. Curabitur pellentesque, urna sit amet laoreet viverra, tellus mauris finibus massa, id finibus nibh turpis sed augue. Donec blandit malesuada purus, sed congue dolor. Maecenas finibus quam a tortor faucibus, ac convallis eros congue. Nunc aliquet pretium semper.',

'Sed vitae nisi nisl. Duis arcu odio, convallis ac tincidunt at, volutpat id ipsum. Sed commodo scelerisque lorem, lobortis sodales libero suscipit eu. Nam sed nisi faucibus, tincidunt sapien sed, dapibus magna. Praesent auctor, sapien at laoreet ullamcorper, eros justo cursus nulla, at consectetur ligula nibh eu justo. Fusce a tincidunt lacus. Vivamus id tincidunt tortor, vitae placerat libero. Nunc vel metus congue, condimentum risus elementum, porttitor felis. Sed vitae aliquet felis. Fusce non sapien quis sapien ullamcorper semper nec quis nibh. Fusce feugiat neque enim, ut efficitur est condimentum vitae. Duis a nisi tortor.',

'Quisque ipsum orci, sodales quis magna at, porta interdum nulla. Duis mauris magna, suscipit eget quam sit amet, porta lacinia libero. Morbi sit amet ex nec turpis ultricies dapibus sit amet vitae ex. In id ullamcorper nisi. Maecenas volutpat libero tellus, id tempus nisi laoreet quis. Nullam accumsan dolor vel lectus gravida fermentum. Aliquam augue ex, sagittis scelerisque sodales interdum, pulvinar nec libero. Donec nec aliquam urna, vitae posuere neque. Nam nulla magna, feugiat ac nunc id, elementum pulvinar magna. Suspendisse laoreet vitae erat quis facilisis. Vivamus tempor consectetur ipsum, sed vehicula libero vulputate et. Duis augue ex, egestas ac dictum non, varius facilisis neque.',

'Nam quis mauris aliquet, semper quam a, congue metus. Fusce porttitor quis dui quis porta. Donec sit amet ullamcorper tortor. Morbi sapien lorem, auctor vitae nulla eu, hendrerit eleifend magna. Mauris a est egestas mauris tempus facilisis. Proin fringilla tristique mauris, a euismod urna. Suspendisse aliquet, risus in molestie mollis, enim massa aliquet felis, in vehicula justo sem convallis tortor. Phasellus nec ultricies tellus. Morbi placerat rutrum mauris, vitae malesuada turpis placerat vel. Nam ac mauris leo. Proin in risus congue, scelerisque velit eget, interdum turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',

'Etiam orci dolor, scelerisque et arcu sed, fringilla lacinia nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean leo felis, ultricies id tristique vitae, auctor id quam. Ut efficitur nunc turpis, et sollicitudin risus luctus a. Nulla eget orci elementum, dignissim felis vel, vulputate arcu. Aenean quis vestibulum dolor. Ut ultrices vestibulum metus. Vivamus egestas laoreet sem, et commodo diam lacinia eget. In rutrum enim magna, eget cursus nunc vulputate a. Vestibulum vehicula eu eros sed commodo. Aliquam et tellus lorem. Proin a tincidunt libero. Nam in orci eget ex ullamcorper euismod auctor sed lectus.',

'Etiam nulla tellus, pharetra sed tellus vel, accumsan placerat lorem. Mauris feugiat odio et accumsan consequat. Quisque orci risus, cursus in ipsum sed, pellentesque tristique ex. Vivamus vitae magna metus. Mauris quis libero varius, gravida velit ut, accumsan arcu. Aliquam viverra pulvinar tellus, ac vulputate enim congue ut. In nulla lectus, dapibus sed lobortis in, pellentesque non dui. Nulla bibendum placerat sapien nec luctus. Quisque tincidunt mollis odio, sed malesuada quam malesuada eget. Maecenas interdum non sapien at iaculis.',

'Mauris sit amet mollis nunc, nec dapibus felis. Fusce in rutrum diam. Mauris pulvinar aliquam turpis at pellentesque. Nullam condimentum nibh enim, et rhoncus ante faucibus in. Aliquam ut sagittis leo. Pellentesque id tortor in justo finibus mollis ac ac justo. Morbi hendrerit commodo ante ac porta. Proin nec sem nec lorem ultricies volutpat. In eu elit hendrerit, tincidunt metus lobortis, egestas risus. Curabitur ut tellus vel turpis rutrum elementum.',

'Maecenas eu tempor libero. Nunc mauris nibh, sodales eu diam at, eleifend facilisis arcu. Nunc non ante iaculis, aliquam odio in, laoreet purus. Nullam nec odio vitae erat euismod eleifend sollicitudin eget quam. Vivamus lacus lorem, ultrices convallis dolor ut, hendrerit congue sapien. Phasellus et posuere leo. Sed quis mauris sed turpis sagittis posuere. Nullam quis risus ornare, accumsan tortor at, rutrum diam. In enim leo, varius non efficitur nec, ornare et risus. Vestibulum et orci neque. Quisque scelerisque orci et pellentesque viverra. Nunc elit lacus, malesuada sollicitudin nibh vitae, lobortis interdum justo. Ut id tempor nisl. Vivamus quis tempus mi. Nulla volutpat cursus massa, quis consequat nisl lacinia ac. Suspendisse eu tellus at neque malesuada lacinia.',

'Donec sapien tortor, ultrices nec ipsum vel, porta gravida orci. Nam vitae tempor urna. Vivamus massa tellus, vulputate non magna ut, lacinia consequat libero. Fusce volutpat metus et tortor rutrum egestas. Donec eget vehicula turpis, id tempus nibh. Nullam porttitor scelerisque magna et porttitor. Morbi vulputate augue id enim placerat, ac pretium orci bibendum. Duis imperdiet fringilla nisi ac ultricies. Etiam a turpis interdum, finibus lorem pharetra, elementum quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ipsum lorem, tincidunt non placerat sit amet, ultricies a urna. Pellentesque maximus lorem ut lorem facilisis luctus.',

'Quisque tincidunt dolor sed odio maximus fringilla. Donec elementum, lorem in efficitur ullamcorper, magna velit iaculis ante, nec vestibulum sem mauris nec elit. Quisque at arcu ac sem dapibus cursus ut eget dui. Nunc fringilla turpis sit amet pretium tincidunt. Sed aliquam eros in turpis efficitur scelerisque. Duis id ipsum nibh. Integer semper finibus sem, at viverra nibh elementum eu. Ut et velit sapien. Nulla est dolor, dictum id fermentum egestas, feugiat quis purus. Nunc tincidunt, libero eu cursus faucibus, sapien massa convallis odio, quis ullamcorper felis orci eu urna. Ut massa lorem, ullamcorper id condimentum nec, pellentesque vel lacus. In a sollicitudin dolor. Nullam quis sapien nec arcu feugiat ultricies eu eget nibh. Vestibulum suscipit odio metus, a porttitor lacus iaculis non.',

'Etiam maximus feugiat nibh semper sodales. Maecenas lacinia, ligula posuere pharetra porta, turpis ligula facilisis velit, interdum vehicula massa ligula eu sapien. Integer hendrerit posuere magna vel ultricies. Fusce iaculis molestie ex sit amet mollis. Maecenas tempus velit diam, vel rutrum odio malesuada ut. Phasellus a sapien feugiat, commodo dui sed, bibendum massa. Cras dapibus risus a leo rutrum auctor. Proin id facilisis quam. Nullam faucibus, nunc ac volutpat fermentum, arcu sapien elementum mi, id elementum dui nulla ac odio. Nunc tincidunt consectetur mi nec semper. Sed ut justo lacus. Pellentesque placerat nisi eu ex mollis, sed iaculis dolor sagittis. Vestibulum quis metus quam. Suspendisse fermentum libero vel hendrerit faucibus. Suspendisse eget maximus diam, non ornare dolor. Pellentesque lacinia orci ac efficitur blandit.',

'Mauris ac mi id odio tristique venenatis et a sapien. Ut condimentum mattis metus iaculis semper. Donec ut arcu diam. Maecenas finibus, dolor ornare mattis imperdiet, justo odio vestibulum ex, in commodo lectus est id diam. Proin sollicitudin facilisis tortor eget venenatis. Pellentesque facilisis massa massa, in gravida tortor ultricies a. Curabitur sed elit fermentum, eleifend neque id, accumsan augue. Sed scelerisque, erat nec vehicula ullamcorper, nisl orci gravida lacus, quis hendrerit nisi metus eget velit. Aliquam quis justo tortor. Quisque suscipit quam velit, quis fringilla sapien sodales id. Donec in nisl sed augue rhoncus vulputate. Aliquam erat volutpat. Proin erat eros, vulputate eu fringilla a, tincidunt ut nulla. Fusce tempus dapibus suscipit. Nunc tristique nulla quis ante maximus, ut sollicitudin ante sollicitudin.',

'Sed molestie purus et egestas consequat. Integer ligula velit, sodales quis tellus sed, imperdiet convallis purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam sed velit augue. Fusce varius nulla dui, sit amet consectetur felis eleifend venenatis. Sed pulvinar ipsum a luctus vestibulum. Vivamus mattis, nibh at rhoncus vehicula, libero arcu mollis lacus, semper bibendum sem nibh non urna. Morbi volutpat arcu lectus, non tincidunt nulla tincidunt ut. Aliquam sit amet odio quis urna imperdiet egestas non pharetra nibh. Morbi tristique massa ut neque pulvinar, a dapibus massa bibendum. Maecenas cursus, magna ut finibus convallis, ex ipsum feugiat tortor, quis tincidunt nulla nulla sit amet dolor. Integer non condimentum quam. Integer ut hendrerit augue, congue luctus sem. Quisque ex libero, rhoncus eget dui eget, dignissim dapibus magna. Suspendisse quis ultricies erat.',

'Maecenas placerat urna felis, eget posuere sapien accumsan sed. Proin ultricies sollicitudin leo, a porttitor felis laoreet vel. Nunc malesuada, metus id ultrices vestibulum, turpis urna faucibus urna, ac egestas ipsum felis a eros. Vivamus pulvinar mollis condimentum. Nulla facilisi. In sodales felis rutrum felis euismod rhoncus. Phasellus tincidunt congue placerat. Cras a ante ac augue posuere congue. Donec faucibus lorem eleifend eros dictum vestibulum. Phasellus fermentum, sapien eu hendrerit vestibulum, lacus odio aliquet sapien, nec dictum augue augue sit amet augue. Fusce vehicula tempus nulla. Cras ut ligula vel dui dictum dapibus eu eget urna. Cras lacinia scelerisque mauris sed iaculis. Mauris vel sollicitudin dui. Morbi et arcu eros. In cursus nulla et tempus commodo.',

'Phasellus interdum laoreet erat ac blandit. Nulla a nunc libero. Suspendisse dictum et tortor a fringilla. Fusce quis leo dolor. Quisque tempor facilisis ante fringilla lacinia. Donec sed nisl sed nibh euismod maximus. Ut pretium ac nunc eu tristique. Nulla dapibus vulputate nulla, et viverra massa semper non. Sed tempor velit ex, vel condimentum lectus ornare pellentesque. Suspendisse varius, libero auctor aliquet accumsan, nisi augue tempus purus, id suscipit mi lectus sit amet elit.',

'Curabitur egestas erat vitae dolor vestibulum, id efficitur quam gravida. Maecenas in aliquam odio. Aliquam neque diam, iaculis id velit at, suscipit pellentesque diam. Donec ornare erat nec pulvinar posuere. Morbi eleifend venenatis condimentum. Aliquam vel turpis non arcu posuere commodo. Pellentesque euismod, tortor in facilisis tempus, elit libero pulvinar massa, eu tristique massa eros at lectus. Etiam faucibus feugiat urna, nec vehicula tortor porttitor ac. Nam viverra consectetur turpis, ac eleifend mi lobortis sit amet. Vestibulum enim velit, rhoncus quis bibendum vitae, tincidunt non ante. Maecenas mattis, leo eget congue ullamcorper, leo magna placerat enim, vel tempus eros nunc in leo. Pellentesque pellentesque posuere enim, in posuere diam tempus sit amet. Suspendisse placerat, velit rhoncus ultrices cursus, turpis velit tempus leo, sed porttitor nibh magna eu eros.',

'Vivamus ultricies elit at tellus convallis fermentum. Etiam ornare tincidunt metus. Morbi consectetur, lacus ut tristique sagittis, odio urna laoreet turpis, a laoreet ex augue id mauris. Donec sagittis maximus ex sed scelerisque. Aliquam et libero at magna fermentum maximus at nec nulla. Suspendisse nec dolor ullamcorper, rutrum sapien sed, commodo tortor. Sed scelerisque sit amet sapien quis iaculis. Nullam mauris turpis, aliquam sit amet eleifend vitae, pharetra at augue. Donec porttitor ullamcorper ligula eget consequat. Nulla facilisi.',

'Nam iaculis feugiat volutpat. Vivamus fringilla, mi ut feugiat finibus, orci ante elementum lectus, et ultricies tellus magna id elit. Praesent laoreet vulputate erat nec aliquam. Sed feugiat quam nec augue maximus commodo nec et diam. Etiam condimentum mauris vel leo euismod, et sodales dui tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed consectetur diam vitae sapien tincidunt, at congue lorem pulvinar. Vestibulum convallis tellus a sodales fermentum. Praesent tincidunt, ligula in accumsan hendrerit, arcu dui tristique odio, a placerat orci urna nec metus. Duis ut efficitur elit, eu facilisis ipsum. Aenean id lectus neque. Praesent ut sapien ut orci consequat rhoncus. Morbi ligula nibh, scelerisque non dignissim mollis, sollicitudin quis nisl. Morbi malesuada lectus enim. Vivamus in urna semper, posuere lacus sed, egestas erat. Vestibulum nisl sem, volutpat vel posuere id, vehicula volutpat ligula.',

'Fusce aliquet gravida eros et tempor. Integer semper sollicitudin elit, vel maximus urna bibendum eu. Donec vel ultricies libero, sit amet elementum risus. Sed et enim ante. Vestibulum sit amet commodo tellus. Nulla pretium nulla sed condimentum pellentesque. Donec quis quam lectus. Sed convallis laoreet semper. Nunc aliquet consequat justo, nec ultricies elit fringilla dapibus. Cras magna ligula, rutrum nec ante ac, pellentesque pharetra felis. Nam accumsan justo arcu.',

'Nulla in interdum urna. Cras velit magna, imperdiet ac dolor vel, efficitur scelerisque tortor. Aliquam ex lorem, iaculis ut odio ac, porttitor tempus enim. Sed vestibulum efficitur erat nec blandit. Sed laoreet lorem a felis consequat imperdiet. Curabitur sodales interdum felis, mollis dignissim ex pellentesque at. In iaculis tellus lectus, nec tristique quam dignissim eget. Aliquam ut risus sit amet sapien aliquam euismod. Mauris quis tempus odio. Mauris malesuada mauris eros, at efficitur dolor semper eget. In aliquam ex vel metus maximus, eget bibendum ipsum dictum. Vestibulum lacus nisl, fermentum vitae rutrum eget, venenatis non purus. Cras at malesuada risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed eget purus eleifend, vehicula nisl in, convallis augue.',

'Donec imperdiet, nibh vel malesuada tristique, elit dolor elementum ligula, eu mollis arcu neque ac mauris. Morbi blandit eleifend ante, in porta sem feugiat ac. Donec luctus, purus vitae fermentum tincidunt, dolor lacus hendrerit sem, quis finibus nisl augue at augue. Integer molestie ligula mauris, nec vestibulum nunc finibus sed. Aliquam placerat libero at metus elementum interdum. Nunc vel iaculis lacus. Duis ornare venenatis mollis. Maecenas vel semper nisl, ac interdum diam.',

'Curabitur in enim sed augue sagittis egestas eu ac est. Etiam imperdiet quis quam convallis dictum. Quisque bibendum feugiat lacus, a faucibus massa lacinia facilisis. Donec orci ipsum, consequat sed dolor vel, ullamcorper faucibus purus. Sed hendrerit mi a eros rutrum, vitae molestie diam convallis. Ut consequat sed purus sit amet pulvinar. Nulla in elementum diam, nec consectetur tortor. Integer diam nibh, hendrerit non sodales vitae, eleifend rutrum ipsum. Curabitur viverra purus pharetra ultricies viverra.',

'Etiam massa augue, mollis sit amet condimentum ut, molestie nec sapien. Sed lacinia ornare lacus, eu auctor odio faucibus cursus. Praesent viverra dolor quis ante pretium, ac auctor enim blandit. Cras pharetra consectetur ante, eget sollicitudin est condimentum non. Donec venenatis elementum enim id consequat. Praesent quis lectus est. In hac habitasse platea dictumst. Ut dictum bibendum tellus, eu porttitor diam elementum sit amet. Nulla dapibus, dolor id tempus malesuada, magna massa accumsan sapien, nec feugiat purus lectus sed tortor. Nullam tempor nisi quis consequat volutpat. Phasellus semper leo sed arcu rutrum luctus. Curabitur luctus libero vel metus viverra tristique. Praesent laoreet nisl ac magna interdum vestibulum. In eleifend posuere volutpat. Sed in vestibulum metus.',

'Cras magna purus, fermentum eget dolor eget, mattis suscipit metus. In tincidunt pretium ante, in hendrerit sem egestas sed. Mauris lacinia, ipsum id blandit mattis, velit velit fringilla quam, a placerat urna dui at sapien. Suspendisse cursus, justo sed rutrum varius, lorem dolor interdum velit, et elementum erat orci id libero. Proin nisi nisi, semper non mauris ut, feugiat convallis mi. Phasellus auctor malesuada nisi vel scelerisque. Sed ornare, lorem et dictum suscipit, erat erat iaculis tortor, eget imperdiet ipsum odio sed augue. Aenean nec lectus lorem. Integer sed pharetra magna. Nunc pulvinar eu diam sit amet ornare. Donec sodales condimentum mauris et aliquam. Sed condimentum nisi ut leo suscipit tempus. Donec elementum lorem neque, in ornare urna condimentum ut.',

'Ut tempor erat non nisi blandit, a vehicula nunc viverra. Proin bibendum augue mi, in malesuada neque tempor eget. Integer tincidunt feugiat nibh sed mattis. Quisque vestibulum tortor at arcu sodales bibendum sit amet ut lectus. Morbi molestie elementum ex, in auctor justo pretium non. Praesent tincidunt nisl arcu, ut pretium sem maximus vel. Nullam ultricies ullamcorper tellus id lacinia.',

'Nam ac vestibulum lectus. Maecenas eget felis sit amet ante convallis sagittis. Ut consequat neque ac ligula tincidunt, eget gravida sem mollis. Quisque et consectetur nisi, vel viverra mi. Cras sit amet ex eu tellus tristique ultrices quis vitae nibh. Maecenas accumsan vulputate dapibus. Nulla facilisi. Nullam blandit felis a leo fringilla tristique. Donec malesuada tincidunt felis, in ultricies erat fermentum faucibus.',

'Aliquam non ullamcorper massa, sit amet eleifend metus. Donec bibendum libero lectus, maximus tristique tellus mollis sed. Suspendisse malesuada neque elit. Aenean porttitor ut enim sed consectetur. Vestibulum a imperdiet arcu. Sed maximus massa ut velit porta, et facilisis metus cursus. Donec nec tortor quis nisi varius eleifend eu ultricies justo. Etiam vitae tincidunt risus. Mauris ac nibh pretium, fringilla quam sed, vehicula eros. Duis enim elit, ultrices at orci eu, semper cursus sem.',

'Nam quis varius lectus. Ut sit amet purus mauris. Fusce bibendum, felis vel cursus tristique, orci justo eleifend lectus, non mollis turpis nibh et elit. Integer id pharetra mi. Duis vestibulum sit amet est sed feugiat. Donec cursus rhoncus aliquam. Cras risus risus, faucibus vitae facilisis venenatis, imperdiet a metus. Quisque ut venenatis ligula. Curabitur sed ligula lacus. Vestibulum ac sagittis ex. Maecenas laoreet magna pulvinar, molestie velit eu, facilisis ex. Vivamus sed imperdiet velit. Ut porttitor arcu ut risus efficitur, nec placerat eros faucibus. Sed pellentesque neque nec scelerisque dignissim. Aliquam in fermentum ligula, eu dapibus eros.',

'Nulla justo augue, porttitor eget finibus in, volutpat eleifend magna. Suspendisse nisl nisi, pharetra eget erat eget, feugiat fermentum mauris. Vestibulum egestas tortor vel sodales laoreet. Nullam vestibulum accumsan nunc, sit amet facilisis lectus. Aliquam tincidunt neque lorem. Aliquam erat volutpat. Suspendisse potenti. Integer blandit tortor enim, eget tempor lorem condimentum sed. Donec risus nunc, aliquam in lacus eget, posuere tristique quam. In sem sem, semper eget rutrum sit amet, faucibus sit amet neque. Integer iaculis dolor tellus, non tristique augue viverra volutpat.',

'Quisque gravida est non ipsum vestibulum, vel feugiat sapien blandit. Aenean eget urna fringilla, faucibus erat id, tincidunt justo. Nullam pharetra ipsum urna, eget tristique purus ultricies in. Vestibulum euismod, est sit amet aliquet laoreet, metus elit tempus libero, vel ornare lectus nisl quis elit. Pellentesque sed justo accumsan, auctor nunc a, pulvinar metus. Nulla sem lacus, ultrices id lectus vitae, commodo finibus tellus. Mauris bibendum enim quis tellus scelerisque, vel finibus nunc feugiat. Nunc congue massa sed pellentesque tincidunt. Nulla fermentum nunc viverra consectetur aliquet. Integer sagittis libero non ultricies consectetur. Cras dictum, libero non tincidunt pulvinar, lorem purus semper sapien, in viverra purus eros vitae risus. Integer dui mi, dictum quis augue sed, viverra finibus nisi. Aenean sit amet felis nisl. Praesent porta volutpat urna, vitae rutrum mauris scelerisque vel. Duis sagittis tristique metus convallis ornare. Etiam gravida mi eu ipsum facilisis, mollis aliquam nisi malesuada.',

'Nunc rutrum lacus sed nisi posuere sodales. Sed lacinia eros sit amet nulla convallis, sed egestas velit faucibus. Duis ut blandit elit. Ut pellentesque dictum arcu quis pretium. Aenean tempus lectus in dui eleifend feugiat. Nam eget lorem euismod, vestibulum dolor eu, tempor turpis. Pellentesque egestas lobortis erat sit amet commodo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse vulputate magna cursus urna malesuada tempus. Donec mollis sem sed leo aliquam pulvinar ac eu purus.',

'Fusce et commodo magna, a auctor felis. Nulla venenatis odio a mi placerat, a dictum nunc malesuada. Nulla facilisi. Sed ac nisl fermentum, ultrices nibh et, efficitur lacus. Etiam iaculis leo sed imperdiet scelerisque. Cras accumsan pretium egestas. Donec et eros diam. Cras pharetra varius leo, ut pretium erat dapibus et. Cras sit amet magna fringilla, dictum ante quis, pulvinar mauris. Maecenas eu felis eget velit consectetur suscipit nec sit amet purus.',

'Quisque sed iaculis orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin placerat ligula eu arcu bibendum cursus. Cras ligula neque, bibendum at feugiat at, dignissim vitae elit. Cras nunc sem, pellentesque tincidunt sem id, ornare fringilla risus. Morbi egestas orci ac pellentesque iaculis. Donec ac rhoncus quam. Curabitur aliquam ut metus ac placerat. Cras posuere varius lectus, ut rhoncus tortor interdum sed. Curabitur enim augue, cursus non libero in, pellentesque consequat massa.',
    'Pellentesque ultricies neque non purus ultricies, sed varius lacus congue. Nulla mollis est eget orci semper imperdiet. Morbi scelerisque vel lectus ut placerat. Morbi sed convallis elit. Ut ex sapien, cursus quis lacinia sed, pellentesque tincidunt magna. Aliquam pellentesque ac leo quis consectetur. Vivamus blandit posuere ipsum semper consequat. Sed feugiat eu lorem a luctus. Sed interdum posuere massa, at tincidunt lorem luctus vel. Nullam congue ex nec volutpat pretium.',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consequat, ligula eget ullamcorper consequat, leo velit feugiat nisi, vel auctor tellus lacus vitae enim. Duis gravida lacinia nulla, ut laoreet nulla laoreet et. Nulla facilisi. Curabitur lacinia elementum justo rhoncus tempus. Nulla facilisi. Quisque feugiat massa non libero suscipit vulputate. Quisque laoreet pellentesque ante vulputate lacinia. In hac habitasse platea dictumst. Donec vulputate, magna non dictum pellentesque, velit dolor fermentum tortor, et luctus mi augue nec mi. Duis sed ligula dui. Aliquam risus mauris, dictum sit amet risus vitae, tristique tristique felis. Etiam nec velit vel felis lobortis sodales. Nullam pellentesque ante in enim ornare cursus vel viverra neque. Phasellus laoreet nunc maximus quam euismod, eu porta orci bibendum. Cras non nibh tincidunt leo ullamcorper venenatis sit amet eu lacus. Etiam posuere dui non ante mollis venenatis.',
    'Suspendisse eget fringilla nisl. Phasellus et malesuada leo. Vestibulum arcu dolor, consequat iaculis tempor et, dapibus in sem. Nulla nibh risus, pretium at accumsan ut, facilisis eu sapien. Nulla facilisi. Nullam et lacus neque. Etiam a massa placerat, ullamcorper leo non, sodales lectus. Mauris vitae dictum dui, id consequat odio. Quisque id ultrices purus.',
    'Etiam dictum ullamcorper diam, eu finibus nibh tincidunt placerat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id rhoncus lacus, fermentum aliquet ante. Donec tincidunt commodo nulla interdum luctus. Nullam placerat tempus varius. Proin non eros vitae leo viverra congue. Nam quis sagittis orci. Aenean eget augue nec sapien varius fringilla eleifend ac enim. Vestibulum volutpat finibus leo, ac vehicula ipsum. Integer congue, nisi ut lobortis dignissim, augue lacus rhoncus felis, vel tristique turpis sem semper libero. Integer sagittis, enim eget tempor viverra, metus sem volutpat neque, at suscipit erat erat eget diam. Proin id vulputate orci. Cras commodo orci sit amet diam ultricies, sed ornare elit lacinia.',
    'Nullam aliquet libero ut libero fringilla faucibus. Phasellus nec elementum tellus. Fusce blandit nunc non bibendum pellentesque. Donec fringilla ligula non ante vehicula auctor. Nam mollis ante ut nunc molestie, at tempus lectus auctor. Nunc nec commodo ligula, lobortis pharetra tortor. Morbi aliquam orci eu neque ultrices, eget hendrerit lorem blandit. Nullam imperdiet, sem sit amet condimentum auctor, leo justo iaculis nulla, eget blandit libero libero sit amet est. Sed a ultricies urna. Mauris imperdiet, enim in euismod aliquet, ligula augue accumsan risus, non malesuada sapien diam id purus. Sed ullamcorper mollis cursus. Mauris imperdiet condimentum fringilla. In at mauris a eros mollis suscipit ut non ipsum. Aenean fringilla, elit at placerat dictum, elit tellus ultricies tellus, a malesuada nisi erat viverra urna. Suspendisse fringilla vel urna quis imperdiet. Sed dapibus sit amet eros ut tincidunt.', 
    'ProNunc efficitur quis justo nec dictum. Ut rhoncus massa ut fringilla pellentesque. Duis lectus dui, pellentesque porta elit vel, sollicitudin dictum dolor. Sed faucibus ultricies auctor. Duis ultricies lacinia arcu. Quisque eu tortor et felis tincidunt commodo. Suspendisse potenti. Nam nisl ante, congue sit amet dignissim id, sodales in est. In sem neque, lobortis vitae massa convallis, tempor sodales leo. Ut blandit dictum lacus ut mollis. Maecenas laoreet rhoncus magna, a fringilla erat aliquet eget. Curabitur et volutpat diam. Suspendisse malesuada scelerisque ex, at posuere orci lacinia quis.in elementum convallis urna, at suscipit nisl aliquam in.'
];

jsBtn.addEventListener('click', function(){
    // Get input from users
    var inputByUser = parseInt(document.getElementById('inputByUser').value);
    // Clear the previous content before starting the loop
    show.innerHTML = '';

    // Prevent users to enter non-numeric or negative number
    if(isNaN(inputByUser) || inputByUser <= 0) {
        alert('Invalid Number');
    };

    //Loop initialing
    for(var i = 0; i < inputByUser; i++) {
        var randomIndex = Math.floor(Math.random() * dummyText.length);
        if(inputByUser > 78) {
            alert('Not Avaible! You\'re allowed only for 78 paragraps.')
            break;
        }
        show.innerHTML += `<p>${dummyText[randomIndex]}</p>`;
    };
});
